# Generated by Django 2.0.1 on 2021-05-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_auto_20210520_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
