# Generated by Django 2.0.1 on 2021-05-19 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_key', models.CharField(max_length=255, unique=True)),
                ('english_definition', models.TextField(blank=True, default='', null=True)),
                ('vn_definition', models.TextField(blank=True, default='', null=True)),
                ('korean_definition', models.TextField(blank=True, default='', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_vocab_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_vocab_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
