# Generated by Django 2.0.1 on 2021-05-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_auto_20210520_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
